# Generated by Django 4.1.6 on 2023-02-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0002_alter_orderitem_size_delete_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('L', 'L'), ('XL', 'XL'), ('M', 'M')], max_length=100, null=True),
        ),
    ]
