# Generated by Django 4.1.6 on 2023-02-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0003_alter_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M')], max_length=100, null=True),
        ),
    ]
