# Generated by Django 4.1.6 on 2023-02-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0006_size_alter_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
