# Generated by Django 4.1.6 on 2023-02-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0009_alter_customer_phone_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='First_Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Last_Name',
        ),
    ]
