# Generated by Django 4.1.6 on 2023-02-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0011_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
