# Generated by Django 4.1.6 on 2023-04-30 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0013_orderitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_address', models.CharField(max_length=200)),
                ('delivery_status', models.CharField(default='Pending', max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hazeapp.order')),
                ('order_items', models.ManyToManyField(to='hazeapp.orderitem')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazeapp.shippingaddress')),
            ],
        ),
    ]
