# Generated by Django 4.1.6 on 2023-04-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0014_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='order_items',
        ),
    ]
