# Generated by Django 4.1.6 on 2023-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0015_remove_delivery_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order_items',
            field=models.ManyToManyField(to='hazeapp.orderitem'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
