# Generated by Django 4.1.6 on 2023-04-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0016_delivery_order_items_alter_delivery_delivery_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
