# Generated by Django 4.1.6 on 2023-05-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0018_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, choices=[('M', 'Medium'), ('S', 'Small'), ('L', 'Large')], max_length=1, null=True),
        ),
    ]
