# Generated by Django 4.1.6 on 2023-05-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0019_delete_size_alter_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
