# Generated by Django 4.1.6 on 2023-05-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0020_remove_orderitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('payer_id', models.CharField(max_length=200, null=True)),
                ('payment_id', models.CharField(max_length=200, null=True)),
                ('payment_token', models.CharField(max_length=200, null=True)),
                ('payment_state', models.CharField(max_length=200, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazeapp.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazeapp.order')),
            ],
        ),
    ]
