# Generated by Django 4.1.6 on 2023-05-11 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazeapp', '0021_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
